spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/service?currentSchema=store
    username: postgres
    password: root

  jpa:
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
